services:
  - type: web
    name: matriz-we-conqui
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    disk:
      name: sqlite
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
